### ISSUE TITLE
Compatibility in noetic

### ISSUE THREAD

**Issue by smoggy-P** [smoggy-P/acl-mapping-px4#1]
A thread to keep track of building this package in ros noetic environment

**Comment by siyuanwu99** [comment]
1.Change C++11 to C++14 in
https://github.com/smoggy-P/acl-mapping-px4/blob/a44f405db76ffc091a0abcfbadf2de0375816b4e/global-mapper/global_mapper/CMakeLists.txt#L21 and
https://github.com/smoggy-P/acl-mapping-px4/blob/a44f405db76ffc091a0abcfbadf2de0375816b4e/global-mapper/global_mapper_ros/CMakeLists.txt#L14

2. Clone https://gitlab.com/mit-acl/fsw/snap-stack/snapstack_msgs.git to the workspace folder.
3. `catkin build`

**Comment by smoggy-P** [comment]
4. In all CmakeList.txt, change minimum cmake requirement from 2.8.3 to 3.0.2

**Comment by smoggy-P** [comment]
Solved by #2
